packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - bufferutil
  - es5-ext
  - esbuild
  - keccak
  - prisma
  - sharp
  - unrs-resolver
  - utf-8-validate
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@prisma/client'
  - contentlayer2
  - core-js
  - protobufjs
