/**
 * Error codes for different Sheets operations
 */
export const SHEETS_ERROR_CODES = {
	QUEST_EXPIRED: "QUEST_EXPIRED",
	QUEST_FINALIZED: "QUEST_FINALIZED",
	QUEST_LIMIT_REACHED: "QUEST_LIMIT_REACHED",
	QUEST_NOT_FOUND: "QUEST_NOT_FOUND",
	SHEET_NOT_FOUND: "SHEET_NOT_FOUND",
	HEADERS_NOT_FOUND: "HEADERS_NOT_FOUND",
	VALUES_NOT_FOUND: "VALUES_NOT_FOUND",
	CLIENT_CREATION_FAILED: "CLIENT_CREATION_FAILED",
	SHEETS_INSTANCE_FAILED: "SHEETS_INSTANCE_FAILED",
	ENV_MISSING: "ENV_MISSING",
	CODE_INVALID: "CODE_INVALID",
	AUTH_FAILED: "AUTH_FAILED",
} as const;

export type SheetsErrorCode =
	(typeof SHEETS_ERROR_CODES)[keyof typeof SHEETS_ERROR_CODES];
